#!/bin/bash

kubectl delete secret ghost-tls
kubectl delete secret ghost
kubectl delete secret 'ghost-test'
kubectl delete configmap nginx-ghost
kubectl delete deployments ghost
kubectl delete deployments ghost-canary
kubectl delete pods ghost
kubectl delete service ghost
kubectl delete ingress ghost
gcloud compute firewall-rules delete allow-130-211-0-0-22
