apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "ghost"
        track: "stable"
    spec:
      containers:
        - name: "nginx"
          image: "nginx:1.9.12"
          ports:
            - containerPort: 80
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - name: "nginx-conf"
              mountPath: "/etc/nginx/conf.d"
        - name: "ghost"
          image: "kelseyhightower/ghost:0.7.7"
          env:
            - name: "NODE_ENV"
              value: "production"
            - name: "GHOST_CONFIG"
              value: "/etc/ghost/config.js"
          livenessProbe:
            httpGet:
              path: /
              port: 2368
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 1
          volumeMounts:
            - name: "ghost"
              mountPath: "/etc/ghost"
            - name: "ghost-tls"
              mountPath: "/etc/ghost/ssl"
      volumes:
        - name: "ghost-tls"
          secret:
            secretName: "ghost-tls"
        - name: "nginx-conf"
          configMap:
            name: "nginx-ghost"
            items:
              - key: "ghost.conf"
                path: "ghost.conf"
        - name: "ghost"
          secret:
            secretName: "ghost"
