apiVersion: v1
kind: Service
metadata:
  labels:
    app: ghost
  name: ghost
  namespace: default
spec:
  ports:
  - nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ghost
  sessionAffinity: None
  type: NodePort
